### PR TITLE
Checking for connection to rabbit message interface on startup

### PR DESCRIPTION
**Pull request by hazmat345**
This addresses beer-garden/beer-garden#38

### CODE REVIEW

**Comment by hazmat345** [comment]
We should give a gentle nudge as far as what's wrong with the error message. "Can't connect to the management interface - is the management plugin enabled?"

**Comment by hazmat345** [comment]
@loganasherjones thoughts on this?

**Comment by loganasherjones** [comment]
LGTM

**Comment by loganasherjones** [comment]
I'd say if we're going to do it for everything else, we might as well check the mongo connection as well.

**Comment by hazmat345** [comment]
This should be good to go once https://github.com/beer-garden/bg-utils/pull/6 is merged in.

**Pull request merged**
